AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/factories.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: 'lf'

Naming/FileName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Style/MultilineBlockChain:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
