version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  redis:
    image: redis:4
    ports:
      - 6379:6379
