<%
random_key = ->(x) {
  path = Rails.root.join("secrets", "#{x}")
  if File.exist?(path)
    key = File.read(path)
  else
    key = SecureRandom.hex(64)
    File.write(path, key)
  end
  return key
}
%>

development:
  secret_key_base: <%= random_key.("secret_key_base-dev") %>
  db_crypt_key:    <%= random_key.("db_crypt_key-dev") %>
  db_crypt_salt:   <%= random_key.("db_crypt_salt-dev") %>

test:
  secret_key_base: <%= random_key.("secret_key_base-test") %>
  db_crypt_key:    <%= random_key.("db_crypt_key-test") %>
  db_crypt_salt:   <%= random_key.("db_crypt_salt-dev") %>

production:
  secret_key_base: <%= random_key.("secret_key_base-prod") %>
  db_crypt_key:    <%= random_key.("db_crypt_key-prod") %>
  db_crypt_salt:   <%= random_key.("db_crypt_salt-prod") %>
